-- liquibase formatted sql

-- changeset annaa:1

CREATE TABLE notification_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    text_msg TEXT,
    notification_time TIMESTAMP
);